name: 'Upload PHPStan to LaraWatch'
description: 'Upload PHPStan results to LaraWatch'
inputs:
  filePath:
    description: 'Full path of the local file you want to upload (e.g. /home/user/file.zip)'
    required: true
  data:
    description: 'Additional data you should want to send within the request (e.g. "{\"foo\":\"bar\"}")'
    required: false
outputs:
  response:
    description: 'The response from the server'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: box
  color: orange
